version: "3.8"

services:
  metabase:
    build: .
    container_name: metabase-duckdb
    ports:
      - "3000:3000"
    environment:
      - MB_PLUGINS_DIR=/home/plugins/
    volumes:
      - ./data:/data
    restart: unless-stopped

networks:
  default:
    name: metabase-network
